version: '3.8'
services:
  #mongodb:
  #  image: mongo
  #  ports:
  #  - 27017:27017
  #  networks:
  #    - my-network
  patient:
    image: patient
    container_name: patient
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - my-network
  note:
    depends_on:
      - patient
    image: note
    container_name: note
    build:
      context: ../P9_Notes
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart:  always
    networks:
      - my-network
  assessment:
    depends_on:
      - patient
    image: assessment
    container_name: assessment
    build:
      context: ../P9_assessments
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    networks:
      - my-network
networks:
  my-network:
    driver: bridge



