version: '3'
services:
  patient:
    image: p9_patient:latest
    container_name: p9_patient
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  notes:
    image: p9-notes:latest
    container_name: p9_note
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
