version: '3'
services:
  #mongodb:
  #  image: mongo
  #  ports:
  #  - 27017:27017
  #  networks:
  #    - my-network
  note:
    depends_on:
      - patient
    image: note
    container_name: note
    build:
      context: ../P9_Notes
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart:  always
    networks:
      - my-network
  patient:
    image: patient
    container_name: patient
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart:  always
    networks:
      - my-network
networks:
  my-network:
    driver: bridge



